<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>bf1e0062-0eab-4d3c-9749-0f46483d8b9f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MonoPraksa.Model.Common\MonoPraksa.Model.Common.csproj" />
    <ProjectReference Include="..\MonoPraksa.Model\MonoPraksa.Model.csproj" />
    <ProjectReference Include="..\MonoPraksa.Repository.Common\MonoPraksa.Repository.Common.csproj" />
    <ProjectReference Include="..\MonoPraksa.Repository\MonoPraksa.Repository.csproj" />
    <ProjectReference Include="..\MonoPraksa.Service.Common\MonoPraksa.Service.Common.csproj" />
    <ProjectReference Include="..\MonoPraksa.Service\MonoPraksa.Service.csproj" />
  </ItemGroup>

</Project>
